name: flutter_application_14
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  date_picker_timeline: ^1.2.3
  date_time_picker: ^2.1.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

  image_picker: ^1.0.5
  intl: ^0.17.0
  lottie: ^2.7.0
  responsive_framework: ^1.1.1
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/
